package com.codigosamurai.entity;

import jakarta.persistence.*;

/**
 * Entidad que representa a un Usuario en la base de datos.
 * Se mapea a la tabla {@code usuarios}.
 *
 * <p>El mapeo se realiza mediante anotaciones JPA estándar interpretadas
 * por Hibernate. Se utiliza el paquete {@code jakarta.persistence}
 * (obligatorio a partir de Hibernate 6.x, que adoptó Jakarta EE 9+).</p>
 *
 * <p>Tabla destino: {@code usuarios}, con las siguientes columnas:</p>
 * <ul>
 *   <li>{@code id BIGINT} — clave primaria autogenerada</li>
 *   <li>{@code nombre VARCHAR(100) NOT NULL}</li>
 *   <li>{@code email VARCHAR(150) NOT NULL UNIQUE}</li>
 * </ul>
 *
 * @see com.codigosamurai.dao.UsuarioDAO
 * @since 1.0
 */
@Entity
@Table(name = "usuarios")
public class Usuario {

    /**
     * Identificador único del usuario.
     *
     * <p>Se mapea a la columna {@code id}. La estrategia
     * {@link GenerationType#IDENTITY} delega la generación del valor a la
     * base de datos (columna autoincremental). En H2 se traduce a
     * {@code BIGINT GENERATED BY DEFAULT AS IDENTITY}.</p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    /**
     * Nombre del usuario.
     *
     * <p>Se mapea a la columna {@code nombre} con restricción
     * {@code NOT NULL} y longitud máxima de 100 caracteres
     * ({@code VARCHAR(100)}).</p>
     */
    @Column(name = "nombre", nullable = false, length = 100)
    private String nombre;

    /**
     * Email del usuario.
     *
     * <p>Se mapea a la columna {@code email} con restricciones
     * {@code NOT NULL} y {@code UNIQUE}. La restricción única evita
     * correos duplicados a nivel de base de datos. Longitud máxima:
     * 150 caracteres ({@code VARCHAR(150)}).</p>
     */
    @Column(name = "email", nullable = false, unique = true, length = 150)
    private String email;

    /**
     * Constructor vacío requerido por la especificación JPA.
     * Hibernate lo invoca por reflexión al materializar entidades
     * desde la base de datos.
     */
    public Usuario() {}

    /**
     * Constructor de conveniencia para crear usuarios en código.
     *
     * @param nombre el nombre del usuario
     * @param email  el email del usuario (debe ser único)
     */
    public Usuario(String nombre, String email) {
        this.nombre = nombre;
        this.email = email;
    }

    /** @return el identificador único del usuario */
    public Long getId() { return id; }

    /** @param id el nuevo identificador (no suele establecerse a mano) */
    public void setId(Long id) { this.id = id; }

    /** @return el nombre del usuario */
    public String getNombre() { return nombre; }

    /** @param nombre el nuevo nombre del usuario */
    public void setNombre(String nombre) { this.nombre = nombre; }

    /** @return el email del usuario */
    public String getEmail() { return email; }

    /** @param email el nuevo email del usuario */
    public void setEmail(String email) { this.email = email; }

    /**
     * Representación textual de la entidad. Útil para logs y depuración.
     *
     * @return cadena con los tres campos del usuario
     */
    @Override
    public String toString() {
        return "Usuario{id=" + id + ", nombre='" + nombre + "', email='" + email + "'}";
    }
}